name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # runs when you push to main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
	python -m pip install --upgrade pip
    	pip install -r requirements.txt
    	pip install pytest
      - name: Run tests
        run: pytest -v

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/Yalda/
            git pull origin main
            source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 YaldaKarimi_simple_profile_flask.py > log.txt 2>&1 &
