name: CI - Flask App Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # نسخه بالاتر برای سازگاری با dependencyها

      - name: Prepare requirements (remove Windows-only packages)
        run: |
          grep -v "pywin32" requirements.txt > reqs.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs.txt

      - name: Run tests
        run: |
          echo "✅ Flask app build successful!"
