name: Deploy to Server

on:
  push:
    branches:
      - main  # وقتی روی شاخه main پوش می‌کنی، اجرا میشه

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Yalda
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart yourapp.service
